# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100
  tensorboard_logdir: tb_asa_finetune

checkpoint:
  save_interval_updates: 2500
  keep_interval_updates: 1
  keep_best_checkpoints: 1
  best_checkpoint_metric: loss
  maximize_best_checkpoint_metric: false
  no_epoch_checkpoints: true
  load_checkpoint_on_all_dp_ranks: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 320000
  min_sample_size: 32000
  normalize: true

dataset:
  num_workers: 4
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 2
  distributed_backend: nccl
  ddp_backend: pytorch_ddp
  distributed_port: 29500
  find_unused_parameters: true

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_ppl
    - pred_ppl
    - codebook_decay
    - asa_I_mu
    - asa_I_sigma
    - asa_Sigma_prime_mu
    - asa_Sigma_prime_sigma

optimization:
  max_update: 25000
  lr: [0.00005]
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]

model:
  _name: dinosr
  extractor_mode: layer_norm
  encoder_layerdrop: 0.05
  dropout_input: 0.0
  dropout_features: 0.0
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
  discrete: true
  codebook_size: 256
  average_top_k_layers: 8
  normal_init_codebook: false
  codebook_init_decay: 0.9
  instance_norm_target_layer: true
  mask_prob: 0.8
  mask_length: 10
  pos_conv_depth: 5
  conv_pos: 95
  ema_decay: 0.999
  ema_end_decay: 0.9999
  ema_anneal_end_step: 15000
  ema_transformer_only: true
  ema_layers_only: true
  require_same_masks: true
  mask_dropout: 0
  enable_asa: true
